name: Android Build

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: npm install

      - name: Build APK with Gradle
        uses: sparkfabrik/android-build-action@v1.5.0
        with:
          project-path: android
          output-path: app-debug.apk
          gradle-task: assembleDebug
